### ISSUE TITLE
Nomenclature: Inline vs. Front Matter

### ISSUE THREAD

**Issue by ryanfitzer** [SapientNitroLA/assemble-documentation#2]
Since we haven't yet written the builder, using the term "front matter" in the readme might confuse things a bit. For example: we've so far identified two different syntaxes that we'll be using for source code documentation: YAML and JSDoc. I think we should instead refer to source-based documentation (documentation that lives in the actual source code) as "inline".

**Comment by vbalcom** [comment]
Add in commit: a345d033c0947371facb3954a7df9123809ac52f
