### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by ryanfitzer** [SapientNitroLA/assemble-documentation#3]
What about using a question to describe each guideline? For example:

# Guidlines #

1. **Useful**: Is the information meant to be useful to the developer or the tool?

2. **Frictionless**: Is this the easiest way to document the feature/module/workflow/etc.?

3. **DRY**: Does the approach cause a duplication of effort?

4. **Evergreen**: Does the approach require unrelated effort to just to stay up to date?

**Comment by vbalcom** [comment]
Added in commit: 8552e6ac22d041f115d78cda372d5058de55c49b
